### ISSUE TITLE
Crashing on start

### ISSUE THREAD

**Issue by bauerj** [fireduck64/jelectrum#8]
Using lobstack as storage backend, jelectrum exits with an exception on every start:

```
electrum@bauerj ~/jelectrum (git)-[master] % java -Xmx8g -jar jar/Jelectrum.jar jelly.conf
special_object_map: GB: 0.000
special_block_store_map: GB: 0.000
tx_map: GB: 0.000
block_store_map: GB: 0.000
block_map: GB: 0.000
block_rescan_map: GB: 0.000
header_chunk_map: GB: 0.000
utxo_trie_map: GB: 0.000
address_to_tx_map: GB: 0.000
tx_to_block_map: GB: 0.000
Adding genesis
MAX QUEUE DEPTH 64 FOR Threading$UserThread
GET HEAD - Exception in thread "main" java.lang.NullPointerException
        at jelectrum.MapBlockStore.getChainHead(MapBlockStore.java:71)
        at com.google.bitcoin.core.AbstractBlockChain.<init>(AbstractBlockChain.java:146)
        at com.google.bitcoin.core.BlockChain.<init>(BlockChain.java:63)
        at com.google.bitcoin.core.BlockChain.<init>(BlockChain.java:55)
        at jelectrum.Jelectrum.<init>(Jelectrum.java:90)
        at jelectrum.Jelectrum.main(Jelectrum.java:24)
```

**Comment by fireduck64** [comment]
A work around:

dpkg-reconfigure locales
export LC_ALL=en_GB.UTF-8
export LANG=en_GB.UTF-8
export LANGUAGE=en_GB.UTF-8

**Comment by fireduck64** [comment]
lol
